version: 0.2
env:
  variables:
    plaintext:
      "STAGE": "dev
phases:
  install:
    runtime-versions:
      nodejs: 10
      commands:
  pre-build:
    commands:
      - npm install
    build:
      commands:
        - npm run build
      post-build:
        commands:
          - aws s3 cp ./build s3://samuli-cb-bucket --recursive